spring.application.name=amc-analytics

spring.datasource.url=jdbc:postgresql://localhost:5432/amc_analytics
# Updated to your actual Mac/Postgres owner name!
spring.datasource.username=davidsegoviano
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# TMDB API Key for Financial Data Enrichment
tmdb.api.key=${TMDB_API_KEY}
